CREATE TABLE `do_links` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `guid` varchar(155) DEFAULT 'global',
  `groupuid` varchar(55) NOT NULL DEFAULT 'hq',
  `menuid` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL,
  `category` varchar(255) DEFAULT NULL,
  `menugroup` varchar(255) DEFAULT NULL,
  `class` varchar(255) DEFAULT NULL,
  `link` varchar(255) DEFAULT '#',
  `iconpath` varchar(255) DEFAULT NULL,
  `tips` varchar(255) DEFAULT NULL,
  `site` varchar(255) DEFAULT '*',
  `privilege` varchar(500) DEFAULT '*',
  `blocked` enum('true','false') DEFAULT 'false',
  `onmenu` enum('true','false') DEFAULT 'true',
  `target` varchar(55) DEFAULT NULL,
  `device` varchar(20) DEFAULT '*',
  `to_check` varchar(200) DEFAULT NULL,
  `weight` int(11) DEFAULT '0',
  `created_by` varchar(155) NOT NULL,
  `created_on` datetime NOT NULL,
  `edited_by` varchar(155) NOT NULL,
  `edited_on` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `do_lists` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `guid` varchar(155) DEFAULT 'global',
  `groupuid` varchar(55) NOT NULL DEFAULT 'hq',
  `groupid` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL,
  `value` varchar(255) DEFAULT NULL,
  `class` varchar(255) DEFAULT NULL,
  `site` varchar(255) DEFAULT '*',
  `sortorder` int(10) NOT NULL,
  `privilege` varchar(50) DEFAULT '*',
  `blocked` varchar(5) DEFAULT 'false',
  `privilegeid` int(11) NOT NULL DEFAULT '0',
  `access_rule` varchar(155) NOT NULL DEFAULT 'privilege',
  `access_level` int(11) NOT NULL DEFAULT '1000',
  `created_by` varchar(155) NOT NULL,
  `created_on` datetime NOT NULL,
  `edited_by` varchar(155) NOT NULL,
  `edited_on` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `my_branches` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `guid` varchar(155) DEFAULT 'global',
  `groupuid` varchar(55) NOT NULL DEFAULT 'hq',
  `branch_code` varchar(50) DEFAULT NULL,
  `company_id` int(11) NOT NULL,
  `name` varchar(200) DEFAULT NULL,
  `category` varchar(155) DEFAULT NULL,
  `type` varchar(155) NOT NULL DEFAULT '',
  `group` varchar(200) DEFAULT NULL,
  `tags` varchar(200) DEFAULT NULL,
  `establishment` date DEFAULT NULL,
  `manager` varchar(155) DEFAULT NULL,
  `mail` varchar(250) DEFAULT NULL,
  `landline` varchar(55) DEFAULT NULL,
  `address` varchar(200) DEFAULT NULL,
  `region` varchar(200) DEFAULT NULL,
  `city` varchar(155) DEFAULT NULL,
  `country` varchar(100) DEFAULT NULL,
  `zipcode` varchar(20) DEFAULT NULL,
  `contact_person1` varchar(255) DEFAULT NULL,
  `contact_designation1` varchar(155) DEFAULT NULL,
  `contact_person2` varchar(255) DEFAULT NULL,
  `contact_designation2` varchar(155) DEFAULT NULL,
  `geofence_enabled` enum('true','false') DEFAULT 'true',
  `geolocation` varchar(250) DEFAULT NULL,
  `geofence_radius` varchar(15) DEFAULT NULL,
  `avatar` varchar(200) DEFAULT NULL,
  `blocked` enum('false','true') NOT NULL DEFAULT 'false',
  `created_by` varchar(155) NOT NULL,
  `created_on` datetime NOT NULL,
  `edited_by` varchar(155) NOT NULL,
  `edited_on` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;

CREATE TABLE `my_company` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `guid` varchar(155) DEFAULT 'global',
  `groupuid` varchar(55) NOT NULL DEFAULT 'hq',
  `com_code` varchar(50) DEFAULT NULL,
  `name` varchar(200) DEFAULT NULL,
  `category` varchar(155) DEFAULT NULL,
  `biz_type` varchar(155) NOT NULL DEFAULT 'proprietorship',
  `tags` varchar(200) DEFAULT NULL,
  `establishment` date DEFAULT NULL,
  `branch_type` varchar(55) NOT NULL DEFAULT 'hq',
  `email` varchar(250) DEFAULT NULL,
  `landline` varchar(55) DEFAULT NULL,
  `address` varchar(200) DEFAULT NULL,
  `state_code` varchar(55) DEFAULT NULL,
  `country` varchar(100) DEFAULT NULL,
  `zipcode` varchar(20) DEFAULT NULL,
  `geoloc` varchar(100) DEFAULT NULL,
  `website` varchar(200) DEFAULT NULL,
  `facebook` varchar(200) DEFAULT NULL,
  `twitter` varchar(200) DEFAULT NULL,
  `instagram` varchar(200) DEFAULT NULL,
  `linkedin` varchar(200) DEFAULT NULL,
  `date_format` varchar(25) NOT NULL DEFAULT 'd/m/Y',
  `time_format` varchar(25) NOT NULL DEFAULT 'H:i:s',
  `timezone` varchar(155) NOT NULL,
  `timezone_utc` int(11) NOT NULL DEFAULT '0',
  `directors` varchar(255) DEFAULT NULL,
  `currency` varchar(5) NOT NULL DEFAULT 'Rs.',
  `tinno` varchar(35) DEFAULT NULL,
  `pan` varchar(55) DEFAULT NULL,
  `gstno` varchar(55) DEFAULT NULL,
  `turn_over` int(11) NOT NULL DEFAULT '0',
  `logo` varchar(250) DEFAULT NULL,
  `letter_head` varchar(255) NOT NULL,
  `about` varchar(255) DEFAULT NULL,
  `setup_params` text,
  `blocked` enum('false','true') NOT NULL DEFAULT 'false',
  `created_by` varchar(155) NOT NULL,
  `created_on` datetime NOT NULL,
  `edited_by` varchar(155) NOT NULL,
  `edited_on` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

CREATE TABLE `my_company_banks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `guid` varchar(155) DEFAULT 'global',
  `groupuid` varchar(55) NOT NULL DEFAULT 'hq',
  `company_id` int(11) NOT NULL DEFAULT '1',
  `bank_name` varchar(155) NOT NULL,
  `bank_code` varchar(25) NOT NULL DEFAULT 'na',
  `bank_branch` varchar(155) NOT NULL,
  `bank_address` varchar(155) DEFAULT NULL,
  `bank_state` varchar(155) NOT NULL,
  `bank_country` varchar(155) NOT NULL DEFAULT 'india',
  `bank_zipcode` varchar(25) DEFAULT NULL,
  `bank_acno_name` varchar(155) DEFAULT NULL,
  `bank_acno` varchar(155) NOT NULL,
  `bank_ifsc_code` varchar(155) NOT NULL,
  `bank_swift_code` varchar(155) NOT NULL,
  `bank_xtras` varchar(255) NOT NULL,
  `bank_notes` varchar(255) NOT NULL,
  `blocked` enum('false','true') NOT NULL DEFAULT 'false',
  `created_by` varchar(155) NOT NULL,
  `created_on` datetime NOT NULL,
  `edited_by` varchar(155) NOT NULL,
  `edited_on` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `my_company_settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `guid` varchar(155) DEFAULT 'global',
  `groupuid` varchar(55) NOT NULL DEFAULT 'hq',
  `company_id` int(11) NOT NULL,
  `param_title` varchar(155) DEFAULT NULL,
  `param_value` varchar(255) DEFAULT NULL,
  `param_module` varchar(75) NOT NULL DEFAULT 'system',
  `param_hash` varchar(92) NOT NULL,
  `blocked` enum('false','true') DEFAULT 'false',
  `privilegeid` int(11) NOT NULL DEFAULT '0',
  `access_rule` varchar(155) NOT NULL DEFAULT 'privilege',
  `access_level` int(11) NOT NULL DEFAULT '1000',
  `created_by` varchar(155) NOT NULL,
  `created_on` datetime NOT NULL,
  `edited_by` varchar(155) NOT NULL,
  `edited_on` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `param_hash` (`param_hash`)
) ENGINE=MyISAM AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

CREATE TABLE `my_departments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `guid` varchar(155) DEFAULT 'global',
  `groupuid` varchar(55) NOT NULL DEFAULT 'hq',
  `company_id` int(11) NOT NULL,
  `branch_code` varchar(25) DEFAULT '*',
  `department_code` varchar(25) NOT NULL,
  `department_name` varchar(200) DEFAULT NULL,
  `department_group` varchar(155) DEFAULT NULL,
  `tags` varchar(200) DEFAULT NULL,
  `department_manager` varchar(155) DEFAULT NULL,
  `geofence_enabled` enum('true','false') DEFAULT 'true',
  `blocked` enum('false','true') NOT NULL DEFAULT 'false',
  `created_by` varchar(155) NOT NULL,
  `created_on` datetime NOT NULL,
  `edited_by` varchar(155) NOT NULL,
  `edited_on` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `department_code` (`department_code`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;